version: '3.5'

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog
    volumes:
      - postgres:/data/db
    networks:
      - network

volumes:
  postgres:

networks:
  network:
    driver: bridge